#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 31, 2018 08:54:00 AM
#    May 31, 2018 09:04:34 AM
#    May 31, 2018 09:14:51 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
    

def set_Tk_var():
    global DataSend
    DataSend = StringVar()
    global DataRec
    DataRec = StringVar()
    global Info
    Info = StringVar()
    global Radio
    Radio = StringVar()

def Send():
    print('GUI_support.Send')
    a=str(DataSend.get())
    print(a)
    DataRec.set(a)
    sys.stdout.flush()

def sel():
    print('GUI_support.sel')
    b=str(Radio.get())
    print(b)
    if b=='1':
        print('bt')
    elif b=='2':
        print('tcp')
    elif b=='3':
        print('udp')
    elif b=='4':
        print('http')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import GUI
    GUI.vp_start_gui()


















